import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const fontSans = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <script async src="./sample-app-js/Config.js"></script>
      <script async src="./core-sdk/FaceTecSDK.js/FaceTecSDK.js"></script>
      <script async src="./sample-app-js/processors/AuthenticateProcessor.js"></script>
      <script async src="./sample-app-js/processors/EnrollmentProcessor.js"></script>
      <script async src="./sample-app-js/processors/LivenessCheckProcessor.js"></script>
      <script async src="./sample-app-js/processors/PhotoIDMatchProcessor.js"></script>
      <script async src="./sample-app-js/processors/PhotoIDScanProcessor.js"></script>
      <script async src="./sample-app-js/utilities/SampleAppUIFunctions.js"></script>
      <script async src="./sample-app-js/utilities/ThemeHelpers.js"></script>
      <script async src="./sample-app-js/utilities/AdditionalScreens.js"></script>
      <script async src="./sample-app-js/utilities/SoundFileUtilities.js"></script>
      <script async src="./sample-app-js/sampleAppController.js?v1"></script>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        {children}
      </body>
    </html>
  );
}
